
const twenties = [
    "The Adventures of Prince Achmed",
"Battleship Potemkin",
"Berlin",
"The Big Parade",
"Body and Soul",
"Broken Blossoms",
"The Cabinet of Dr. Caligari",
"The Cameraman",
"The Cat and the Canary",
'The Circus',
'The Crowd',
"Destiny",
"The Docks of New York",
"Faust",
"The Flying Ace",
"Foolish Wives",
"The General",
"The Gold Rush",
"The Golem",
"The Hands of Orlac",
'The Kid',
'The Last Laugh',
'Laura',
"Lifeboat",
"The Lodger",
"The Lost World",
"The Mark of Zorro",
"Meet Me in St. Louis",
'Metropolis',
'The Navigator',
'Nosferatu',
'Our Hospitality',
'A Page of Madness',
'Pandora’s Box',
'The Passion of Joan of Arc',
'The Penalty',
"The Phantom Carriage",
"The Phantom of the Opera",
'Safety Last!',
"Sally of the Sawdust",
"Seven Chances",
"Sherlock Jr.",
"Spies",
'Steamboat Bill Jr.',
'Strike',
'Sunrise',
"The Thief of Baghdad",
'Underworld',
'The Unknown',
'Variety',
'Wings',
"Within Our Gates",
"A Woman of Paris",
]

const thirties = [
    'The Adventures of Robin Hood',
'All Quiet on the Western Front',
'Angels with Dirty Faces',
'Animal Crackers',
'L’Atlante',
'The Blue Angel',
"Bride of Frankenstein",
'Bringing Up Baby',
'The Champ',
'City Lights',
'Dead End',
'Destry Rides Again',
'Dinner at Eight',
'Dracula',
'Duck Soup',
'Earth',
'Footlight Parade',
'Frankenstein',
"Freaks",
'Fury',
'Grand Illusion',
'I am a Fugitive from a Chain Gang',
'It Happened One Night',
'It’s a Gift',
'Jezebel',
'King Kong',
'M',
'Make Way for Tomorrow',
'Le Million',
'Modern Times',
'Monkey Business',
'The Most Dangerous Game',
'Mr. Deeds Goes to Town',
'Mr. Smith Goes to Washington',
'My Man Godfrey',
'A Night at the Opera',
'Ninotchka',
'A Nous la Liberte',
'Rules of the Game',
'Sabotage',
"She Done Him Wrong",
"Snow White and the Seven Dwarves",
'Stagecoach',
'The Story of a Cheat',
'Sylvia Scarlett',
'The Thin Man',
'Top Hat',
'Vampyr',
'The Whole Town’s Talking',
'The Women',
'The 39 Steps',
]

const forties = [
    'Arsenic and Old Lace',
'Bambi',
'The Bank Dick',
'Bedlam',
'The Best Years of Our Lives',
'Bicycle Thieves',
'The Big Sleep',
'Black Narcissus',
'Casablanca',
'Cat People',
'Children of Paradise',
'Citizen Kane',
'Cover Girl',
'The Curse of the Cat People',
'Dance, Girl, Dance',
'Detour',
'Double Indemnity',
'For Me and My Gal',
'Foreign Correspondent',
'Gilda',
'The Grapes of Wrath',
'The Great Dictator',
'Heaven Can Wait',
'His Girl Friday',
'Isle of the Dead',
'The Lady Eve',
'The Lady of Shanghai',
'Little Caesar',
'The Maltese Falcon',
"A Matter of Life and Death",
'Meet Me in St. Louis',
'Mildred Pierce',
'Monsieur Verdoux',
'Mr. Blandings Builds His Dream House',
'Now, Voyager',
'The Ox-Bow Incident',
'Paisan',
'Panique', 
'The Philadelphia Story', 
"Rebecca",
"The Red Shoes",
'Road to Morocco',
'Rome, Open City',
'Rope',
"Sullivan’s Travels",
'The Third Man',
"To Be or Not to Be",
"The Treasure of the Sierra Madre",
'Two-Faced Woman',
"The Wolf Man",
]

const fifties = [
    "Ace in the Hole",
'All About Eve',
'Anatomy of a Murder',
"...And God Created Woman",
"Animal Farm",
'The Barefoot Contessa',
'The Bridge on the River Kwai',
'The Creature from the Black Lagoon',
'Dial M for Murder',
'Elevator to the Gallows',
'Eyes Without a Face',
"Gentlemen Prefer Blondes",
'Gojira',
"The Golden Coach",
'The Hidden Fortress',
'High Noon',
'High Society',
'How to Marry a Millionaire',
'Johnny Guitar',
'Ikiru',
'The Incredible Shrinking Man',
'Kiss Me Deadly',
"The Lady and the Tramp",
"Lola Montes",
"M. Hulot’s Holiday",
'The Man from Laramie',
'Monkey Business',
'The Naked Spur',
'Nights of Cabiria',
'North by Northwest',
'On the Waterfront',
'Pather Panchali',
'Paths of Glory',
'Plucking the Daisy',
'Rashomon',
'Rear Window',
'La Ronde',
'Sansho the Bailiff',
'The Searchers',
'Seven Samurai',
'The Seventh Seal',
'Singin in the Rain',
'Smiles of a Summer Night',
'Some Like It Hot',
'La Strada',
'Strangers on a Train',
'Summer with Monika',
'Sunset Boulevard',
'Throne of Blood',
'To Catch a Thief',
'Ugetsu',
'Umberto D',
'Vertigo',
'The Wages of Fear',
'Wild Strawberries',
'Winchester ‘73',
'Witness for the Prosecution',
'The Wrong Man',
'12 Angry Men',
'The 400 Blows',
'20,000 Leagues Under the Sea',
]

const sixties = [
    'Andrei Rublev',
'The Apartment',
'Band of Outsiders',
'Barbarella',
'Batman: The Movie',
'Belle Du Jour',
'The Birds',
'Black Girl',
'Black Sabbath',
'Blow-Up',
'Bonnie & Clyde',
'Breathless',
'Bye Bye Birdie',
'Carnival of Souls',
'Cat Ballou',
'Cat on a Hot Tin Roof',
'Cleo from 5 to 7',
'Come Drink with Me',
'Cool Hand Luke',
'Daisies',
'Divorce Italian Style',
'La Dolce Vita',
'Dr. Strangelove',
'The Exterminating Angel',
'Eyes Without a Face',
'Faster Pussycat! Kill! Kill!',
'The Fireman’s Ball',
'Friday Foster',
'Gate of Flesh',
'Goldfinger',
'The Good, the Bad & the Ugly',
'The Great Escape',
'Harakiri',
'A Hard Day’s Night',
'Help!',
'High & Low',
'I am Cuba',
'I am Curious (Yellow)',
'In the Heat of the Night',
'Inherit the Wind',
'Judgement at Nuremberg',
'Jules & Jim',
'Juliet of the Spirits',
'Lawrence of Arabia',
'Let It Be',
'Lolita',
'The Magnificent Seven',
'Marriage Italian Style',
'Mary Poppins',
'Masculin Feminin',
'The Masque of the Red Death',
'Memories of Underdevelopment',
'The Music Man',
'My Fair Lady',
'Night of the Living Dead',
'Once Upon a Time in the West',
'Onibaba',
'Persona',
'The Planet of the Apes',
'Playtime',
'Psycho',
'Repulsion',
'Romeo & Juliet',
'The Shooting',
'They Shoot Horses, Don’t They?',
'A Shot in the Dark',
'To Kill a Mockingbird',
'Tom Jones',
'The Trial',
'Umbrellas of Cherbourg',
'Viridiana',
'Vivre sa Vie',
'Wait Until Dark',
'Weekend',
'West Side Story',
'Who Are You Polly Maggoo?',
'Who’s Afraid of Virginia Woolf',
'Yojimbo',
'Young Girls of Rochefort',
'Z',
"Zazie dans le Metro",
'8 1/2',
'101 Dalmatians',
'2 or 3 Things I Know About Her',
'2001: A Space Odyssey',
]

const seventies = [
    'Alien',
'All That Jazz',
'Amarcord',
'Apocalypse Now',
'Assault on Precinct 13',
'Attack of the Killer Tomatoes',
'Barry Lyndon',
'Being There',
'Belladonna of Sadness',
'The Big Bird Cage',
'Brewster McCloud',
'Caged Heat',
'Carrie',
'Chinatown',
'A Clockwork Orange',
'Coffy',
'Coming Home',
'Daughters of the Darkness',
'Dawn of the Dead',
'Death Race 2000',
'The Deer Hunter',
'Disco Godfather',
'Dolemite',
'Drunken Master',
'Enter the Dragon',
'Eraserhead',
'The Exorcist',
'F for Fake',
'Fantastic Planet',
'Five Deadly Venoms',
'Foxy Brown',
'The Godfather',
'The Godfather Part II',
'Halloween',
'Harold & Maude',
'House',
'JD’s Revenge',
'The Killing of a Chinese Bookie',
'Lady Snowblood',
'The Last Picture Show',
'The Last Waltz',
'Life of Brian',
'The Long Goodbye',
'Love & Anarchy',
'Lupin the III: The Castle of Cagliostro',
'MASH',
'McCabe & Mrs. Miller',
'Mikey & Nicky',
'Monty Python & the Holy Grail',
'Network',
'Nosferatu',
'The Omen',
'One Flew Over the Cuckoo’s Nest',
'The Parallax View',
'Phantom of the Paradise',
'Picnic at Hanging Rock',
'The Pink Panther Strikes Again',
'Real Life',
'Rocky',
'Roma',
'Shaft',
'Spirit of the Beehive',
'Stalker',
'The Student Nurses',
'Super Fly',
'Suspiria',
'Targets',
'Taxi Driver',
'A Touch of Zen',
'Two Tons of Turquoise to Taos Tonight',
'Up!',
'The Warriors',
'The Wicker Man',
'Wizards',
'A Woman Under the Influence',
'Woodstock',
'Young Frankenstein',
'3 Women',
]

const eighties = [
    'Adventures in Babysitting',
'The Adventures of Buckaroo Bonzai',
'After Hours',
'Akira',
'Alice',
'Aliens',
'Amadeus',
'Atlantic City, USA',
'Back to the Future',
'Beverly Hills Cop',
'The Big Chill',
'Bill & Ted’s Excellent Adventure',
'Blade Runner',
'Blue Velvet',
'Brazil',
'Broadcast News',
'Bull Durham',
'Castle in the Sky',
'Chopping Mall',
'Cinema Paradiso',
'Clue',
'The Color Purple',
'Come and See',
'The Cook, the Thief His Wife and Her Lover',
'Dangerous Liaisons',
'Das Boot',
'Dead Poet’s Society',
'Dead Ringers',
'The Dead Zone',
'Death Spa',
'Die Hard',
'Do the Right Thing',
'E.T.',
'The Elephant Man',
'Enter the Ninja',
'Evil Dead II',
'Fanny & Alexander',
'Fast Times at Ridgemont High',
'A Fish Called Wanda',
'Fitzcarraldo',
'Flash Gordon', 
'The Fly',
'Footloose',
'For All Mankind',
'Full Metal Jacket',
'Good Morning, Vietnam',
'Grave of the Fireflies',
'The Great Muppet Caper',
'Hard Boiled',
'Howard the Duck',
'Indiana Jones and the Raiders of the Lost Ark',
'Kiki’s Delivery Service',
'The King of Comedy',
'Koyaanisqatsi',
'Labyrinth',
'The Last Metro',
'The Last Temptation of Christ',
'Lethal Weapon',
'Lifeforce',
'The Little Mermaid',
Local Hero,
Look Who’s Talking,
Midnight Run,
Mishima: A Life in Four Chapters,
My Dinner with Andre,
My Neighbor Totoro,
Paris, Texas,
Planes, Trains & Automobiles,,
Platoon,
Police Story,
Poltergeist,
Predator,
The Princess Bride,
Raging Bull,
Raising Arizona,
Ran,
The Right Stuff,
Risky Business,
Romancing the Stone,
Scanners,
Scarface,
Sex, Lies and Videotape,
The Shining,
Shogun Assassin,
Stand By Me,
Star Trek: The Wrath of Khan,
Steele Justice,
Tampopo,
Teen Wolf,
Terms of Endearment,
The Thin Blue Line,
The Thing,
The Tin Drum,
The Toxic Avenger,
Tron,
True Stories,
Vagabond,
The Verdict, 
Victor/Victoria,
Videodrome,
When Harry Met Sally…,
Where is My Friend’s House?,
Who Framed Roger Rabbit,
Wings of Desire,
]





const nineties = [
    The Adventures of Priscilla, Queen of the Desert,
Air Force One,
Aladdin,
All About My Mother,
American Movie,
Anastasia,
Apollo 13,
Babe,
Babe: Pig in the City,
Baraka,
Barton Fink,
Batman Returns,
Before Sunrise,
The Big Lebowski,
Big Night,
Bill & Ted’s Bogus Journey,
The Blair Witch Project,
Boogie Nights,
Bowfinger,
Boyz in the Hood,
Boogie Nights,
A Bug’s Life,
But I’m a Cheerleader,
Carlito’s Way,
Casino,
Chaplin,
Chunking Express,
Clueless,
Contact,
The Craft,
Crumb,
Daughters of the Dust,
Dead Man,
Death Becomes Her,
Deep Blue Sea,
Deep Cover,
Demolition Man,
Don’t Tell Mom the Babysitter’s Dead,
The Double Life of Veronique,
The Ear,
Eyes Wide Shut,
The Faculty,
Fargo,
La Femme Nikita,
Fight Club,
The Firm,
The Fisher King,
Forrest Gump,
Four Weddings and Funeral,
Friday,
Ghost,
Glengarry Glen Ross,
Goldeneye,
Goodfellas,
Good Will Hunting,
The Green Mile,
Grosse Point Blank,
Groundhog Day,
La Haine,
Heat,
Heavenly Creatures,
Hoop Dreams,
Jackie Brown,
The Ice Storm,
In & Out,
Independence Day,
The Island of Dr. Moreau,
Jurassic Park,
The Killer,
King of New York,
Kundun,
L.A. Confidential,
Last Action Hero,
The Last of the Mohicans,
The Last Seduction,
The Legend of the Drunken Master,
Leon: The Professional,
The Lion King,
Lock, Stock and Two Smoking Barrels,
Lone Star,
Lost Highway,
Man Bites Dog,
The Matrix,
Mulan,
My Own Private Idaho,
Naked,
Orlando,
Out of Sight,
Paranormal Activity,
Philadelphia,
The Piano,
Point Break,
Porco Rosso,
Princess Mononoke,
Pulp Fiction,
Quiz Show,
Raise the Red Lantern,
Reservoir Dogs,
A Ride with the Devil,
Ringu,
Robin Hood: Men in Tights,
Romeo + Juliet,
Rumble in the Bronx,
Run Lola Run,
Rushmore,
Safe,
Saving Private Ryan,
Scream,
Sense and Sensibility,
Se7en,
Shakespeare in Love,
The Shawshank Redemption,
The Silence of the Lambs,
The Sixth Sense,
Sleepy Hollow,
Speed,
Star Trek: First Contact,
Stealing Beauty,
Tank Girl,
Taste of Cherry,
Terminator 2: Judgement Day,
That Thing You Do!,
Three Colors: Blue,
Three Colors: Red,
Three Colors: White,
Thelma & Louise,
The Thin Red Line,
Timecop,
Titanic,
To Die For,
To Wong Foo, Thanks for Everything, Julie Newmar,
Toy Story,
Topsy-Turvy,
Trainspotting,
The Truman Show,
Twister,
Unforgiven,
The Virgin Suicides,
Wag the Dog,
The Wedding Banquet,
When We Were Kings,
You’ve Got Mail,
12 Monkeys,
]

const oughties = [
    A.I. Artificial Intelligence,
Across the Universe,
Adaptation,
Amelie,
Atonement,
Audition,
Bamako,
Batman Begins,
Beaches of Agnes,
Being John Malkovich, 
Big Fish,
Bloody Sunday,
The Bourne Identity,
Can’t Hardly Wait,
Capote,
Casino Royale,
Cast Away,
Catch Me if You Can,
Charlie Bartlett,
Charlie’s Angels,
Children of Men,
City of God,
Cloverfield,
Coffee & Cigarettes,
Collateral,
The Conjuring,
Coraline,
Crouching Tiger, Hidden Dragon,
The Curious Case of Benjamin Button,
The Dark Knight,
Death at a Funeral,
The Departed,
The Devil Wears Prada,
District 9,
The Dreamers,
Downfall,
Eternal Sunshine of the Spotless Mind,
The Fantastic Mr. Fox,
Femme Fatale,
Finding Nemo,
The Fountain,
Frances Ha,
Frida,
The Full Monty,
The Girlfriend Experience,
The Good, the Bad, the Weird,
Gosford Park,
Happy Go-Lucky,
Haywire,
Hedwig and the Angry Inch,
Hero,
The Host,
Hot Fuzz,
Howl’s Moving Castle,
The Hurt Locker,
Junebug,
Just Like Heaven,
I Heart Huckabees,
The Imposter,
Inglourious Basterds, 
In the Mood for Love,
The Informant!,
Inside Man,
King Kong,
Kiss Kiss Bang Bang,
Kung Fu Hustle,
Legally Blonde,
Let the Right One In,
The Life Aquatic,
The Lives of Others,
Lost in Translation,
Lucy,
Memento,
Michael Clayton,
Miss Congeniality,
Monster’s Inc,
Music & Lyrics,
No Country for Old Men,
Oldboy,
OSS 117: Cairo, Nest of Spies,
Panic Room,
Pan’s Labyrinth,
Paris, Je T’Aime,
Persepolis,
The Pianist,
Ponyo,
The Prestige,
The Princess Diaries,
Reefer Madness: The Movie Musical,
Rize,
The Room,
Russian Ark,
Save the Last Dance,
Saved!,
A Serious Man,
Shanghai Noon,
Shaolin Soccer,
Shaun of the Dead,
Shoot Em Up,
A Single Man,
Slumdog Millionaire,
Snatch,
Something’s Gotta Give,
Speed Racer,
Spellbound,
Spirited Away,
Stardust,
Sweeney Todd: The Demon Barber of Fleet Street,
Swimming Pool,
Synecdoche, New York,
Tears of the Black Tiger,
There Will Be Blood,
Together,
Up,
Vera Drake, 
A Very Long Engagement,
La Vie en Rose,
Waking Life,
Wall-E,
Wendy & Lucy,
Wet Hot American Summer,
Y Tu Mama Tambien,
Zodiac,
8 Mile,
]

const twentyTens = [
    Abducted in Plain Sight,
Ad Astra,
All is Lost,
Always Be My Maybe,
American Animals,
American Honey,
Annihilation,
Apollo 11,
Argo,
The Artist,
Arrival,
Attack the Block,
The Babadook,
Bad Times at the El Royale,
The Ballad of Buster Scruggs,
The Big Short,
Black Panther,
Blade Runner 2049,
Blancieves,
Black Swan,
The Blade of the Immortal,
Blue is the Warmest Color,
Blue Ruin,
Booksmart,
Boyhood,
Bridge of Spies,
Burning,
Call Me By Your Name,
Cameraperson,
Can You Ever Forgive Me?,
Carol,
Christopher Robin,
CitizenFour,
Clouds of Sils Maria,
Coco,
Coherence,
Cold War,
Columbus,
Combat Obscura,
The Comedy,
Creed,
Crimson Peak,
Crown Heights,
Damsel,
Diary of a Teenage Girl,
Dolemite is My Name,
Drive,
The Duke of Burgundy,
Dunkirk,
Edge of Seventeen,
Edge of Tomorrow,
Eighth Grade,
Elle,
Embrace of the Serpent,
Enough Said,
Enter the Void,
Ex Machina,
Exit Through the Gift Shop,
The Farewell,
Fast Five,
The Favourite,
First Reformed,
Florence Foster Jenkins,
The Florida Project,
Force Majeure,
Frances Ha, 
Free Fire,
Free Solo,
Game Night,
Get Out,
A Ghost Story,
A Girl Walks Home Alone at Night,
The Girl with the Dragon Tattoo,
Gloria Bell,
Gone Girl,
Good Time,
The Grand Budapest Hotel,
The Great Beauty,
The Green Room,
Greener Grass,
Guardians of the Galaxy,
The Guest,
The Guilty,
Hail, Caesar!,
Halloween,
The Handmaiden,
Hanna,
The Hate U Give,
Hell or High Water,
Her,
Her Smell,
Hereditary,
High Flying Bird,
Holy Motors,
Homecoming,
The House I Live In,
House of Tolerance,
Hustlers,
If Beale Street Could Talk,
L'Illusioniste,
Inception,
Inherent Vice,
Inside Llewyn Davis,
Inside Out,
The Intern,
Interstellar,
It Comes at Night,
It Follows,
Jackie,
Jane Fonda: In Five Acts,
John Wick,
Jupiter Ascending,
Kedi,
The King,
The King’s Speech,
Kingsman: The Secret Service
Knives Out,
Kong: Skull Island,
La La Land,
Lady Bird,
Lady Macbeth, 
Leave No Trace,
The LEGO Movie,
Lemon,
Life of Pi,
The Lighthouse,
Lincoln,
Little Women,
Logan,
Long Shot,
Looper,
The Lost City of Z,
Mad Max: Fury Road,
Magic Mike,
Manchester By the Sea,
Mandy,
Margin Call,
Marriage Story,
Mary Poppins Returns,
The Master,
Meek’s Cutoff,
The Meg,
Melancholia,
Mercury 13,
Meru,
Midsommar,
Minding the Gap,
Les Miserables,
Miss Sloane,
Mission: Impossible - Ghost Protocol, 
Mission: Impossible - Fallout,
Molly’s Game,
Moneyball,
Moonlight,
Moonrise Kingdom,
Mother!,
The Muppets,
Muppets Most Wanted,
Mustang,
The Nice Guys,
Noah,
Okja,
Once Upon a Time... in Hollywood,
Pacific Rim,
Paddington 2, 
Pain and Gain,
Parasite,
Personal Shopper,
Peterloo,
Phantom Thread,
Phoenix,
A Pigeon Who Sat on a Branch Reflecting on Existence,
Portrait of a Lady on Fire,
Prisoners,
Prometheus,
Prospect,
The Raid: Redemption,
The Report,
The Revenant,
Rise of the Planet of the Apes,
Risk,
Rocketman,
Roma,
Room,
Rush,
Saving Mr. Banks,
Scott Pilgrim Vs. the World,
Selma,
The Shape of Water,
Shaun the Sheep,
Shoplifters,
Short Term 12,
Shutter Island,
Sing Street,
The Sisters Brothers,
Skyfall,
Slow West,
The Social Network,
Son of Saul,
Sorry to Bother You,
Source Code,
The Souvenir,
Speed Racer,
Spider-Man: Into the Spider-Verse,
Spotlight,
Spring Breakers,
The Square,
A Star is Born,
Stoker,
Stories We Tell,
Support the Girls,
Tabloid,
Take Shelter,
Tangerine,
They Came Together,
Tim & Eric's Billion Dollar Movie,
The Tree of Life,
Triple Frontier,
True Grit,
Uncle Boonme Who Can Recall His Past Lives,
Uncut Gems,
Under the Skin,
Us,
War Horse,
What We Do in the Shadows,
Whiplash,
Widows,
Wild Rose,
The VVitch,
The Wolf of Wall Street,
Wonder Woman,
You Were Never Really Here,
Your Name.,
Zero Dark Thirty,
10 Cloverfield Lane,
12 Years a Slave,
13th,
20 Feet from Stardom,
20th Century Women,
]

const twentyTwenties = [
    An American Pickle,
    Bad Education,
    Beanpole,
    Bill & Ted Face the Music,
    Birds of Prey,
    Black is King,
    Blow the Man Down,
    Da 5 Bloods,
    Dick Johnson is Dead,
    The Father,
    Fireball,
    First Cow,
    Happiest Season,
    Horse Girl,
    I’m Thinking of Ending Things,
    Judas and the Black Messiah,
    Kajillionaire,
    The King of Staten Island,
    Let Them All Talk,
    Love & Monsters,
    Lucky Grandma,
    Ma Rainey’s Black Bottom,
    Mank,
    Minari,
    Miss Americana,
    The Nest,
    News of the World,
    Nomadland,
    The Old Guard,
    Onward,
    Palm Springs,
    Possessor,
    Save Yourselves!,
    She Dies Tomorrow,
    Sorry We Missed You,
    Soul,
    Sound of Metal,
    The Trial of the Chicago 7,
    The Trip to Greece,
    Vast of Night,
    The Way Back,
    Wolfwalker,
];
